USE codeup_test_db;
SHOW tables;


# CREATE TABLE IF NOT EXISTS users (
#       `id` INT NOT NULL AUTO_INCREMENT,
#       `first_name` VARCHAR(50) NOT NULL,
#       `last_name` VARCHAR(100) NOT NULL,
#       `user_name` VARCHAR(26) NOT NULL,
#       `user_email` VARCHAR(100) NOT NULL,
#       PRIMARY KEY (`id`),
#       UNIQUE INDEX `username_UNIQUE` (`user_name` ASC),
#       UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC))


-- MySQL Script generated by MySQL Workbench
-- Mon Nov  2 11:27:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
      `id` INT NOT NULL AUTO_INCREMENT,
      `first_name` VARCHAR(50) NOT NULL,
      `last_name` VARCHAR(100) NOT NULL,
      `user_name` VARCHAR(26) NOT NULL,
      `user_email` VARCHAR(100) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE INDEX `username_UNIQUE` (`user_name` ASC),
      UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ad_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ad_post (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(50) NOT NULL,
    `content` TEXT(255) NOT NULL,
    `user_id` INT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_user_id_idx` (`user_id` ASC),
    CONSTRAINT `fk_user_id`
        FOREIGN KEY (`user_id`)
            REFERENCES `mydb`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
   `id` INT NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS post_category (
      `post_id` INT NULL,
      `category_id` INT NULL,
      INDEX `fk_category_id_idx` (`category_id` ASC),
      INDEX `fk_post_id_idx` (`post_id` ASC),
      CONSTRAINT `fk_post_id`
          FOREIGN KEY (`post_id`)
              REFERENCES `mydb`.`ad_post` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION,
      CONSTRAINT `fk_category_id`
          FOREIGN KEY (`category_id`)
              REFERENCES `mydb`.`categories` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
